build: update chat test.

diff --git a/.github/workflows/docker-Deployment-test.yml b/.github/workflows/docker-Deployment-test.yml
--- a/.github/workflows/docker-Deployment-test.yml
+++ b/.github/workflows/docker-Deployment-test.yml
@@ -44,16 +44,87 @@ jobs:
 
       - name: Test OpenIM Server
         run: |
-            docker logs openim-server
-    
+          docker logs openim-server
+
       - name: Test OpenIM chat
         run: |
-            docker logs openim-chat
+          check_error() {
+            echo "Response: $1"
+            errCode=$(echo $1 | jq -r '.errCode')
+            if [ "$errCode" != "0" ]; then
+              errMsg=$(echo $1 | jq -r '.errMsg')
+              echo "Error: $errMsg"
+              exit 1
+            fi
+          }
+
+          # Test register
+          response1=$(curl -X POST -H "Content-Type: application/json" -H "operationID: imAdmin" -d '{
+            "verifyCode": "666666",
+            "platform": 3,
+            "autoLogin": true,
+            "user":{
+            "nickname": "test12312",
+            "areaCode":"+86",
+            "phoneNumber": "12345678190",
+            "password":"test123456"
+            }
+          }' http://127.0.0.1:10008/account/register)
+          check_error "$response1"
+          userID1=$(echo $response1 | jq -r '.data.userID')
+          echo "userID1: $userID1"
+
+          response2=$(curl -X POST -H "Content-Type: application/json" -H "operationID: imAdmin" -d '{
+            "verifyCode": "666666",
+            "platform": 3,
+            "autoLogin": true,
+            "user":{
+            "nickname": "test22312",
+            "areaCode":"+86",
+            "phoneNumber": "12345678290",
+            "password":"test123456"
+            }
+          }' http://127.0.0.1:10008/account/register)
+          check_error "$response2"
+          userID2=$(echo $response2 | jq -r '.data.userID')
+          echo "userID2: $userID2"
+
+          # Test login
+          login_response=$(curl -X POST -H "Content-Type: application/json" -H "operationID: imAdmin"  -d '{
+            "platform": 3,
+            "areaCode":"+86",
+            "phoneNumber": "12345678190",
+            "password":"test123456"
+          }' http://localhost:10008/account/login)
+          check_error "$login_response"
+
+          # Test get admin token
+          get_admin_token_response=$(curl -X POST -H "Content-Type: application/json" -H "operationID: imAdmin" -d '{
+            "secret": "openIM123",
+            "platformID": 2,
+            "userID": "imAdmin"
+          }' http://127.0.0.1:10002/auth/get_admin_token)
+          check_error "$get_admin_token_response"
+          adminToken=$(echo $get_admin_token_response | jq -r '.data.token')
+          echo "adminToken: $adminToken"
+
+          # Test send message
+          send_msg_response=$(curl -X POST -H "Content-Type: application/json" -H "operationID: imAdmin" -H "token: $adminToken" -d '{
+            "sendID": "'$userID1'",
+            "recvID": "'$userID2'",
+            "senderPlatformID": 3,
+            "content": {
+              "content": "hello!!"
+            },
+            "contentType": 101,
+            "sessionType": 1
+           }' http://127.0.0.1:10002/msg/send_msg)
+           check_error "$send_msg_response"
 
       - name: stop docker compose
         run: |
           docker compose down
-          
+
   go-test:
     name: Benchmark Test with go ${{ matrix.go_version }} on ${{ matrix.os }}
     runs-on: ${{ matrix.os }}
@@ -65,8 +136,8 @@ jobs:
     #   pull-requests: write
     strategy:
       matrix:
-        os: [ ubuntu-latest ]
-        go_version: [ "1.22.x" ]
+        os: [ubuntu-latest]
+        go_version: ["1.22.x"]
 
     steps:
       - name: Checkout Docker repository
@@ -75,7 +146,7 @@ jobs:
       - name: Checkout SDK repository
         uses: actions/checkout@v4
         with:
-          repository: 'openimsdk/openim-sdk-core'
+          repository: "openimsdk/openim-sdk-core"
           path: ${{ env.SDK_DIR }}
 
       - name: Set up Go ${{ matrix.go_version }}
@@ -104,4 +175,3 @@ jobs:
           cd integration_test
           mkdir data
           go run main.go -lgr 0.8 -imf -crg -ckgn -ckcon -sem -ckmsn -u 20 -su 5 -lg 2 -cg 2 -cgm 3 -sm 10 -gm 10 -reg
-
