Update sync-server-version.yaml

diff --git a/.github/workflows/sync-server-version.yaml b/.github/workflows/sync-server-version.yaml
--- a/.github/workflows/sync-server-version.yaml
+++ b/.github/workflows/sync-server-version.yaml
@@ -26,11 +26,23 @@ jobs:
 
       - name: Fetch the latest tag of openim-server
         id: server-tag
-        run: echo "SERVER_TAG=$(curl -s https://api.github.com/repos/openimsdk/open-im-server/tags | jq -r '.[0].name')" >> $GITHUB_ENV
+        run: |
+          SERVER_TAG=$(curl -s https://api.github.com/repos/openimsdk/open-im-server/tags | jq -r '.[0].name')
+          if [[ $SERVER_TAG == "null" ]]; then
+            echo "No new tags found for openim-server. Exiting..."
+            exit 78; # Exits the job early with success status
+          fi
+          echo "SERVER_TAG=${SERVER_TAG}" >> $GITHUB_ENV
 
       - name: Fetch the latest tag of chat
         id: chat-tag
-        run: echo "CHAT_TAG=$(curl -s https://api.github.com/repos/openimsdk/chat/tags | jq -r '.[0].name')" >> $GITHUB_ENV
+        run: |
+          CHAT_TAG=$(curl -s https://api.github.com/repos/openimsdk/chat/tags | jq -r '.[0].name')
+          if [[ $CHAT_TAG == "null" ]]; then
+            echo "No new tags found for chat. Exiting..."
+            exit 78; # Exits the job early with success status
+          fi
+          echo "CHAT_TAG=${CHAT_TAG}" >> $GITHUB_ENV
 
       - name: Update .env.example with the latest tags
         run: |
@@ -43,16 +55,20 @@ jobs:
           git config --local user.name "kubbot"
           git add .env.example
           git commit -m "Update server and chat image versions to ${SERVER_TAG} and ${CHAT_TAG}" || echo "No changes to commit"
-        #   git push
+          git push || echo "No changes to push or push failed"
 
-      - name: Test the setup
+      - name: Check if tag already exists
+        id: check-tag
         run: |
-          make init
-          docker compose up -d
-          # Add some test cases or a health check here
-          echo "Assume tests passed for now"
+          if git rev-parse "${SERVER_TAG}-${CHAT_TAG}" >/dev/null 2>&1; then
+            echo "Tag ${SERVER_TAG}-${CHAT_TAG} already exists. Skipping tag creation."
+            echo "SKIP_TAG_CREATION=true" >> $GITHUB_ENV
+          else
+            echo "SKIP_TAG_CREATION=false" >> $GITHUB_ENV
+          fi
 
       - name: Create and Push New Tag
+        if: env.SKIP_TAG_CREATION == 'false'
         run: |
           git tag "${SERVER_TAG}-${CHAT_TAG}"
           git push origin "${SERVER_TAG}-${CHAT_TAG}"
